spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChengHaoHappy/config-repo.git
          username: ChengHaoHappy
          password: union1995116
          basedir: E:/Space/Idea_workplace/springcloud-samples/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 开放 bus-refresh 接口，以便配合 bus 实现 配置的动态刷新
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 8080
